In [1]:
%matplotlib inline
import sklearn
import pandas
import numpy

import trackml.dataset
import trackml.score

import os.path
import sys

In [59]:
path_to_train = 'train_100_events.zip'
event_prefix = "event000001001"
#path = os.path.join(path_to_train, event_prefix)
path = 'train_sample.zip'

events = pandas.DataFrame()
datas = []
for e in trackml.dataset.load_dataset(path, nevents=1):
    event_id, hits, cells, particles, truth = event
    data = hits.merge(truth)
    data['event_id'] = event_id
    events = data
    datas.append(data)
events = pandas.concat(datas)

events.head()

hit_id          x         y       z  volume_id  layer_id  module_id  \
0       1 -64.409897 -7.163700 -1502.5          7         2          1   
1       2 -55.336102  0.635342 -1502.5          7         2          1   
2       3 -83.830498 -1.143010 -1502.5          7         2          1   
3       4 -96.109100 -8.241030 -1502.5          7         2          1   
4       5 -62.673599 -9.371200 -1502.5          7         2          1   

   event_id         particle_id         tx        ty      tz            tpx  \
0      1000                   0 -64.411598 -7.164120 -1502.5  250710.000000   
1      1000   22525763437723648 -55.338501  0.630805 -1502.5      -0.570605   
2      1000                   0 -83.828003 -1.145580 -1502.5  626295.000000   
3      1000  297237712845406208 -96.122902 -8.230360 -1502.5      -0.225235   
4      1000  418835796137607168 -62.659401 -9.375040 -1502.5      -0.281806   

             tpy           tpz    weight  
0 -149908.000000 -956385.00000  0.000000  
1       0.028390     -15.49220  0.000010  
2 -169767.000000 -760877.00000  0.000000  
3      -0.050968      -3.70232  0.000008  
4      -0.023487      -6.57318  0.000009

In [62]:
events['event_id'].unique(), len(events)

(array([1000]), 120939)

In [47]:
events['volume_id'].unique()

array([ 7,  8,  9, 12, 13, 14, 16, 17, 18])

In [48]:
events['layer_id'].unique()

array([ 2,  4,  6,  8, 10, 12, 14])

In [55]:
len(events['module_id'].unique())

3028

In [63]:
events[events['particle_id'] == 22525763437723648]

hit_id          x         y       z  volume_id  layer_id  module_id  \
1          2 -55.336102  0.635342 -1502.5          7         2          1   
1419    1420 -55.162201  0.604841 -1497.5          7         2        106   
1459    1460 -47.975498  0.311848 -1302.5          7         4          1   
3169    3170 -47.812302  0.327322 -1297.5          7         4        106   
3233    3234 -40.622799  0.088046 -1102.5          7         6          1   
5342    5343 -40.438801  0.098098 -1097.5          7         6        106   
5423    5424 -35.480598 -0.008800  -962.5          7         8          1   
5481    5482 -35.330101 -0.023294  -958.0          7         8          4   
7866    7867 -35.312302 -0.004440  -957.5          7         8        106   
7950    7951 -30.333700 -0.105277  -822.5          7        10          1   

      event_id        particle_id         tx        ty      tz       tpx  \
1         1000  22525763437723648 -55.338501  0.630805 -1502.5 -0.570605   
1419      1000  22525763437723648 -55.154400  0.621779 -1497.5 -0.569794   
1459      1000  22525763437723648 -47.988098  0.315591 -1302.5 -0.568883   
3169      1000  22525763437723648 -47.804100  0.308733 -1297.5 -0.571445   
3233      1000  22525763437723648 -40.626099  0.087326 -1102.5 -0.569940   
5342      1000  22525763437723648 -40.442200  0.082538 -1097.5 -0.570204   
5423      1000  22525763437723648 -35.475899 -0.024284  -962.5 -0.569773   
5481      1000  22525763437723648 -35.310101 -0.027160  -958.0 -0.571644   
7866      1000  22525763437723648 -35.291698 -0.027451  -957.5 -0.571617   
7950      1000  22525763437723648 -30.315399 -0.095482  -822.5 -0.570993   

           tpy      tpz    weight  
1     0.028390 -15.4922  0.000010  
1419  0.027264 -15.4928  0.000008  
1459  0.021994 -15.4929  0.000006  
3169  0.020847 -15.4933  0.000005  
3233  0.015274 -15.4934  0.000005  
5342  0.013872 -15.4940  0.000006  
5423  0.010668 -15.4940  0.000009  
5481  0.008881 -15.4949  0.000011  
7866  0.009012 -15.4950  0.000014  
7950  0.006231 -15.4951  0.000016

In [66]:
events[events['particle_id'] == 418835796137607168]

hit_id          x        y       z  volume_id  layer_id  module_id  \
4          5 -62.673599 -9.37120 -1502.5          7         2          1   
37        38 -62.473598 -9.36801 -1498.0          7         2          4   
1467    1468 -54.161701 -8.55084 -1302.5          7         4          1   
1512    1513 -53.989101 -8.56516 -1298.0          7         4          4   
3243    3244 -45.713699 -7.63520 -1102.5          7         6          1   
3301    3302 -45.514000 -7.61032 -1098.0          7         6          4   
5414    5415 -39.845299 -6.92257  -962.5          7         8          1   
5488    5489 -39.655998 -6.87240  -958.0          7         8          4   
7958    7959 -34.012001 -6.11239  -822.5          7        10          1   
8012    8013 -33.816399 -6.08747  -818.0          7        10          4   

      event_id         particle_id         tx       ty      tz       tpx  \
4         1000  418835796137607168 -62.659401 -9.37504 -1502.5 -0.281806   
37        1000  418835796137607168 -62.466999 -9.35879 -1498.0 -0.279476   
1467      1000  418835796137607168 -54.164299 -8.57144 -1302.5 -0.278422   
1512      1000  418835796137607168 -53.973499 -8.55208 -1298.0 -0.278900   
3243      1000  418835796137607168 -45.696701 -7.65350 -1102.5 -0.277665   
3301      1000  418835796137607168 -45.507702 -7.63102 -1098.0 -0.274887   
5414      1000  418835796137607168 -39.853500 -6.91513  -962.5 -0.273934   
5488      1000  418835796137607168 -39.665501 -6.88994  -958.0 -0.274974   
7958      1000  418835796137607168 -34.013500 -6.09420  -822.5 -0.273872   
8012      1000  418835796137607168 -33.826401 -6.06726  -818.0 -0.273267   

           tpy      tpz    weight  
4    -0.023487 -6.57318  0.000009  
37   -0.023703 -6.57378  0.000008  
1467 -0.029102 -6.57385  0.000005  
1512 -0.027307 -6.57455  0.000004  
3243 -0.032837 -6.57462  0.000004  
3301 -0.032938 -6.57526  0.000006  
5414 -0.036526 -6.57532  0.000008  
5488 -0.036689 -6.57600  0.000010  
7958 -0.040391 -6.57606  0.000012  
8012 -0.038382 -6.58593  0.000015